require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '13.0'

target 'TruSdkReactNativeExample' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  pod 'tru-sdk-react-native', :path => '../..'

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  
  # Flipper-Folly doesn't compile under Xcode12.5 (as of 28 April 2021)
  # Enable below if you are using Xcode 12.4
  #use_flipper!({ 'Flipper' => '0.86.0' })
  #post_install do |installer|
  #  flipper_post_install(installer)
  #end
end
